/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DegenToken } from "./DegenToken";
export type { Lock } from "./Lock";
export type { Staking } from "./Staking";
