/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DegenToken__factory } from "./DegenToken__factory";
export { Lock__factory } from "./Lock__factory";
export { Staking__factory } from "./Staking__factory";
